ALTER TABLE `ORDER` DROP FOREIGN KEY `FK_ORDER_fk_user`
ALTER TABLE `ORDER` DROP FOREIGN KEY `FK_ORDER_fk_item`
ALTER TABLE PROVINCE DROP FOREIGN KEY FK_PROVINCE_iidcountry
DROP TABLE ITEM
DROP TABLE `ORDER`
DROP TABLE USER
DROP TABLE COUNTRY
DROP TABLE PROVINCE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
